# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: test
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: go build .
      - name: Test
        run: go test ./...
